### ISSUE TITLE
WP's admin-ajax.php returns Invalid User

### ISSUE THREAD

**Issue by lukasag** [timersys/facebook-login#3]
After authorizing the APP the loading animation in the button keeps running forever because **admin-ajax.php from Wordpress returns {"error":"Invalid User"}**.

**?me** 
  Returned desired data
**?api_kei**
  Returned nothing else than the OK (200) status code as expected.
**admin-ajax.php**
  Returned {"error":"Invalid User"}

![error_wp](https://cloud.githubusercontent.com/assets/7580681/9596310/9f382d02-5049-11e5-8c76-83e6a11bd913.jpg)

**Comment by timersys** [comment]
HI Lukasag I need to do some tests in order to reproduce the error but my guess is that when it tries to recover an existing user  it fails because a username with fb id doesn't exist.
Then it tries to register the user but that email already exist so it fails again.

I need to fix two things in here
1- Try to get existing user by email and username instead of just username, so existing users can still log with their fb accounts
2- If something fails, remove the spinning thing and show error.

**Comment by timersys** [comment]
new version released

**Comment by lukasag** [comment]
Working like a charm, you are fast.
Thanks for the update!
